export const pricingData = [
  {
    country: 'Afghanistan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '9.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Albania',
    connectionMobile: '0.50 kr',
    mobilePerMin: '4.90 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Algeria',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Andorra',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.50 kr/min',
  },
  {
    country: 'Angola',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Anguilla',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Antigua And Barbuda',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Argentina',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Armenia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Aruba',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Ascension Island',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Australia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Austria',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Azerbaijan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Bahamas',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Bahrain',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Bangladesh',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Barbados',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Belgium',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Belize',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Benin',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Bermuda',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Bhutan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Bolivia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Bosnia And Herzegovina',
    connectionMobile: '0.50 kr',
    mobilePerMin: '4.90 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Botswana',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Brazil',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Brunei Darussalam',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Bulgaria',
    connectionMobile: '0.50 kr',
    mobilePerMin: '4.90 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Burkina Faso',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Burundi',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Cambodia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Cameroon',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Canada',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Cape Verde',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Cayman Islands',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Central African Republic',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Chile',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'China',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Colombia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Comoros',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Congo',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Congo, The Democratic Republic Of The',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Cook Islands',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Costa Rica',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Croatia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Cuba',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Cyprus',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.73 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Czech Republic',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Denmark',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.45 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.45 kr/min',
  },
  {
    country: 'Diego Garcia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Djibouti',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Dominica',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Dominican Republic',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Ecuador',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Egypt',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'El Salvador',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Equatorial Guinea',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Eritrea',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Estonia',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.73 kr/min',
    connectionLandline: '0.00 kr',
    landlinePerMin: '0.00 kr/min',
  },
  {
    country: 'Ethiopia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Faroe Islands',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Fiji',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Finland',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.73 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.73 kr/min',
  },
  {
    country: 'France',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'French Guiana',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'French Polynesia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Gabon',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Gambia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Georgia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Germany',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Ghana',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Gibraltar',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Greece',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Greenland',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Grenada',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Guadeloupe',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Guam',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Guatemala',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Guinea',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Guinea-Bissau',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Guyana',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Haiti',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Honduras',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Hong Kong',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Hungary',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Iceland',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'India',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Indonesia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'International Networks',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.00 kr/min',
  },
  {
    country: 'Iran',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.50 kr/min',
  },
  {
    country: 'Iraq',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Ireland',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Israel',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Italy',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Ivory Coast',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Jamaica',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Japan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Jordan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Kenya',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Kiribati',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Kuwait',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Kyrgyzstan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Laos',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Lebanon',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Lesotho',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Liberia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Libyan Arab Jamahiriya',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Liechtenstein',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Lithuania',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Luxembourg',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Macao',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Macedonia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Madagascar',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Malawi',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Malaysia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Maldives',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Mali',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Malta',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Marshall islands',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '22.00 kr/min',
  },
  {
    country: 'Martinique',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Mauritania',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Mauritius',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Mexico',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Micronesia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Moldova',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Monaco',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Mongolia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Montenegro',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Montserrat',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Morocco',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Mozambique',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Myanmar',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Namibia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Nauru',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '28.00 kr/min',
  },
  {
    country: 'Nepal',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Netherlands',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Netherlands Antilles',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'New Caledonia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'New Zealand',
    connectionMobile: '0.00 kr',
    mobilePerMin: '2.73 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'Nicaragua',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Niger',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Nigeria',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Niue',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'North Korea',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Norway',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Philippines',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Poland',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Portugal',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Reunion',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '11.90 kr/min',
  },
  {
    country: 'Romania',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Russian Federation',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.73 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Serbia',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Slovenia',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Spain',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Sweden',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.62 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.12 kr/min',
  },
  {
    country: 'Switzerland',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'Syrian Arab Republic',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '9.40 kr/min',
  },
  {
    country: 'Tanzania',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Thailand',
    connectionMobile: '0.50 kr',
    mobilePerMin: '0.28 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Turkey',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '0.73 kr/min',
  },
  {
    country: 'United Arab Emirates',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'United Kingdom',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.00 kr',
    landlinePerMin: '0.28 kr/min',
  },
  {
    country: 'United States',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.00 kr',
    landlinePerMin: '1.28 kr/min',
  },
  {
    country: 'Uruguay',
    connectionMobile: '0.50 kr',
    mobilePerMin: '2.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Vietnam',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Virgin Islands, British',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Virgin Islands, U.S.',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.70 kr/min',
  },
  {
    country: 'Yemen',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
];
