export const pricingData = [
  {
    country: 'Afghanistan',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Albania',
    connectionMobile: '0.50 kr',
    mobilePerMin: '4.90 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Algeria',
    connectionMobile: '0.50 kr',
    mobilePerMin: '3.70 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Andorra',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '1.50 kr/min',
  },
  {
    country: 'Angola',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Anguilla',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Antigua And Barbuda',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
  {
    country: 'Argentina',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '2.90 kr/min',
  },
  {
    country: 'Armenia',
    connectionMobile: '0.00 kr',
    mobilePerMin: '0.00 kr/min',
    connectionLandline: '0.50 kr',
    landlinePerMin: '7.40 kr/min',
  },
];
